### ISSUE TITLE
Why use localtime_r

### ISSUE THREAD

**Issue by barrybingo** [mdvorak/ccronexpr#4]
why use localtime_r() when can use localtime()

I compiled this on mips_24kc and localtime_r was not working then I saw that in the code you are not even using the second parameter so can just use localtime() which on my system worked fine.

e.g.
calendar = cron_time(&date, &calval);

calval is never used !!!

**Comment by mdvorak** [comment]
This is from original upstream repository, but here is why:

> The localtime() function converts the calendar time timep to broken-down time representation, expressed relative to the user's specified timezone. The function acts as if it called [tzset](https://linux.die.net/man/3/tzset)(3) and sets the external variables tzname with information about the current timezone, timezone with the difference between Coordinated Universal Time (UTC) and local standard time in seconds, and daylight to a nonzero value if daylight savings time rules apply during some part of the year. The return value points to a statically allocated struct which **might be overwritten by subsequent calls to any of the date and time functions**. The localtime_r() function does the same, but stores the data in a user-supplied struct. It need not set tzname, timezone, and daylight.

**Comment by mdvorak** [comment]
There is a better maintained fork of the original repo, you can also try it out
https://github.com/exander77/supertinycron

**Comment by barrybingo** [comment]
Thanks for the feedback :)
